### ISSUE TITLE
facing problem in installation

### ISSUE THREAD

**Issue by meenabsrawat** [capcom6/sms-gateway#54]
hello i have tried all method as you describe in read.me file 
can you help me regarding installation 

thanks

**Comment by capcom6** [comment]
Hello,

Thank you for reaching out and for trying the installation methods described in the README.

Firstly, I would like to point out that in most situations, it is not necessary to run your own server; you can use our public cloud server for free. For more information on this, please visit: https://sms.capcom.me/getting-started/public-cloud-server/

However, if you are interested in running your own private server, this does require some technical knowledge. You can find more detailed instructions and information in our documentation here: https://sms.capcom.me/getting-started/private-server/

If you encounter any problems during the installation, could you please provide a detailed description of the issue? This should include any logs from your actions or screenshots of the errors you are experiencing. This additional information will greatly assist us in helping you resolve the problem more effectively.

**Comment by meenabsrawat** [comment]
i have tried but not installed properly do you have any other documentation or docker file for centos 7 or ubuntu

**Comment by capcom6** [comment]
Can you provide any details about the installation methods you've attempted, the steps you've taken, and the results?

In our documentation at https://sms.capcom.me/getting-started/private-server/, there are two links with instructions on how to install a private server with Docker:
- One is from a user contribution: https://github.com/capcom6/android-sms-gateway/discussions/50
- Another is a guide that I've prepared: https://github.com/capcom6/sms-gateway/tree/master/deployments/docker-compose-proxy

Please try following these guides and let me know how it goes. Your feedback would be greatly appreciated.

**Comment by meenabsrawat** [comment]
thanks for your quick reply now i have installed system on my server 

does api support receiving replies to the conversation and associating it with a sent message ID


Thanks

**Comment by capcom6** [comment]
Thank you for the update, and I'm glad to hear that you've successfully installed the app on your server.

Unfortunately, the current version of the app does not support receiving replies. The primary focus of the app at this time is sending messages. 

I may consider adding this feature in future releases, but I cannot provide any guarantees. For further discussion and updates on this topic, you can follow this issue: https://github.com/capcom6/android-sms-gateway/issues/16

Thank you for your understanding.

Do you have any more questions about the private server installation, or may I close the issue?
