### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by nmally** [capcom6/sms-gateway#96]
I have an older version of mysql. Not sure why the install script is failing. Here's the error and server version. User has full database privileges. 

Server: localhost via TCP/IP
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 8.0.15 - MySQL Community Server - GPL
Protocol version: 10

PS C:\docker\sms> docker run -p 3000:3000 -v "${PWD}/config.yml:/app/config.yml" capcom6/sms-gateway:latest
2024/11/04 16:17:18 OK   20221007133357_init.sql (136.69ms)
{"level":"error","ts":1730737038.8452222,"caller":"fxevent/zap.go:59","msg":"invoke failed","error":"ERROR 20230925232629_ext_id_index.sql: failed to run SQL migration: failed to execute SQL query \"CREATE UNIQUE INDEX IF NOT EXISTS `unq_messages_id_device` ON `messages`(`ext_id`, `device_id`);\": Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `unq_messages_id_device` ON `messages`(`ext_id`, `device_id`)' at line 1","stack":"github.com/capcom6/go-infra-fx/cli.GetModule\n\t/go/pkg/mod/github.com/capcom6/go-infra-fx@v0.0.2/cli/module.go:30\ngithub.com/capcom6/sms-gateway/internal/sms-gateway.Run\n\t/go/src/internal/sms-gateway/app.go:51\nmain.main\n\t/go/src/cmd/sms-gateway/main.go:27\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271\n","function":"github.com/capcom6/go-infra-fx/db.Migrate()","module":"cli","stacktrace":"go.uber.org/fx/fxevent.(*ZapLogger).logError\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/fxevent/zap.go:59\ngo.uber.org/fx/fxevent.(*ZapLogger).LogEvent\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/fxevent/zap.go:193\ngo.uber.org/fx.(*module).executeInvoke\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/module.go:289\ngo.uber.org/fx.(*module).executeInvokes\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/module.go:274\ngo.uber.org/fx.(*module).executeInvokes\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/module.go:268\ngo.uber.org/fx.New\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/app.go:503\ngithub.com/capcom6/sms-gateway/internal/sms-gateway.Run\n\t/go/src/internal/sms-gateway/app.go:50\nmain.main\n\t/go/src/cmd/sms-gateway/main.go:27\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271"}
{"level":"error","ts":1730737038.8453157,"caller":"fxevent/zap.go:59","msg":"start failed","error":"ERROR 20230925232629_ext_id_index.sql: failed to run SQL migration: failed to execute SQL query \"CREATE UNIQUE INDEX IF NOT EXISTS `unq_messages_id_device` ON `messages`(`ext_id`, `device_id`);\": Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `unq_messages_id_device` ON `messages`(`ext_id`, `device_id`)' at line 1","stacktrace":"go.uber.org/fx/fxevent.(*ZapLogger).logError\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/fxevent/zap.go:59\ngo.uber.org/fx/fxevent.(*ZapLogger).LogEvent\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/fxevent/zap.go:215\ngo.uber.org/fx.(*App).Start.func1\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/app.go:640\ngo.uber.org/fx.(*App).Start\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/app.go:645\ngo.uber.org/fx.(*App).run\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/app.go:587\ngo.uber.org/fx.(*App).Run\n\t/go/pkg/mod/go.uber.org/fx@v1.20.1/app.go:578\ngithub.com/capcom6/sms-gateway/internal/sms-gateway.Run\n\t/go/src/internal/sms-gateway/app.go:58\nmain.main\n\t/go/src/cmd/sms-gateway/main.go:27\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271"}

**Comment by capcom6** [comment]
Hello!

Thank you for bringing this to my attention. The migrations were originally created for MariaDB, but there are some syntax differences between MySQL and MariaDB. In this case, the problem was with the `IF NOT EXISTS` clause.

I've fixed the migrations in PR #97. Please try using the `capcom6/sms-gateway:pr-97` image and let me know if it works for you.

I would greatly appreciate your feedback on this solution.
